version: '3.8'

volumes:
  static_value:
  media_value:
  db_data:

services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  backend:
    container_name: backend
    image: 1oneome1/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: frontend
    image: 1oneome1/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: gateway
    image: nginx:1.21.3-alpine
    ports:
      - "8000:80"
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
      - frontend
